### ISSUE TITLE
Is there a way to listen specific transition event?

### ISSUE THREAD

**Issue by selossevianney** [K-Phoen/DoctrineStateMachineBundle#15]
Hello,

I have many listeners that react on transition events but in each listeners I have to test if the transition is the one that allow this listener to do what it's meant to. The thing that bother me is that every listeners are reacting on each transitions and I don't want this. 

Is there a way to have each transition notifying is own event ? 

I think of create a unique listener that react on finite transition event and that will dispatch specific event on specific transition. Am I missing something or is this the only way?

Sorry for my english, hope you've understood.

**Comment by K-Phoen** [comment]
If you read [Finite/StateMachine/StateMachine.php](https://github.com/yohang/Finite/blob/master/src/Finite/StateMachine/StateMachine.php#L133-L141)'s code, you'll see that there are specific events for each transition that is triggered.

**Comment by selossevianney** [comment]
Right... I missed something. Thank you for this quick answer. You made my day.

**Comment by K-Phoen** [comment]
It was a pleasure :)
