### ISSUE TITLE
entity persist

### ISSUE THREAD

**Issue by juanolon** [K-Phoen/DoctrineStateMachineBundle#16]
Hello,
so one silly question. the entities are not saved automatically when i call `->apply('state')`. right?
i haven't found any `->flush()` method on the repository, this means, after i call `->apply('state')` i need to persist the object with the entity manager, and flush it when i'm done.

greetings

**Comment by K-Phoen** [comment]
Yep, you're the one who knows when the entity can/need to be persisted so the bundle never does it itself.

**Comment by juanolon** [comment]
yes, i thought so. but wasn't sure. thanks for the quick answer :)
