### ISSUE TITLE
[Feature request] Add graphviz support

### ISSUE THREAD

**Issue by ksn135** [K-Phoen/DoctrineStateMachineBundle#6]
Create a console commands to work with current graph using ***dot*** (graphviz) binary.
```
# app/console dsm:graphviz:generate-dot article_state_machine
digraph G {
    new -> reviewed [label="review"];
    reviewed -> accepted [label="accept"];
    accepted -> published [label="publish"];
    new -> rejected [label="reject"];
    reviewed -> rejected [label="reject"];
    accepted -> rejected [label="reject"];
    published -> rejected [label="reject"];
}
# app/console dsm:graphviz:generate-image article_state_machine --type=png > 2.png
```
![2](https://cloud.githubusercontent.com/assets/230304/5342876/857a68fc-7f12-11e4-984e-72b9df5d264c.png)

What do you think about it? (I could make a PR).

**Comment by K-Phoen** [comment]
As the PR yohang/Finite#17 is still not merged, I implemented myself this feature in this bundle.
